version: "3"

services:
 simple_rabbitmq_message:
   build: .
   container_name: rabbitmq-message-rest
   ports:
     - 3000:3333
   depends_on: 
     - rabbitmq

 rabbitmq:
   image: "rabbitmq:3.8-management-alpine"
   container_name: simple-rabbit-mq-container
   hostname: rabbitmq
   ports:
     - "15672:15672" #porta do painel admin
     - "5672:5672" 
   environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=admin