version: "3"

services:
 simple-rabbitmq-project:
   build: .
   container_name: rabbitmq-project-rest
   environment: 
    - RABBITMQ_USER=admin
    - RABBITMQ_PASS=admin
    - RABBITMQ_PORT=5672
    - RABBITMQ_HOST=rabbitmq
    - TOPIC=message
    - PORT=3333
   ports:
     - 3000:3333
   depends_on: 
     - rabbitmq

 rabbitmq:
   image: "rabbitmq:3.8-management-alpine"
   container_name: simple-rabbit-mq-container
   hostname: rabbitmq
   ports:
     - "15672:15672" #porta do painel admin
     - "5672:5672" 
   environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=admin